services:
  backend:
    build:
      context: .
    volumes:
      - ..:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: sleep infinity
    stop_grace_period: 2s
  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    volumes:
      - ../database/create.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
